// crates/powerlink-rs/src/nmt/events.rs
use crate::PowerlinkError;

/// Defines NMT State Command IDs used in ASnd(NMT_COMMAND) frames.
/// (Reference: EPSG DS 301, Appendix 3.7, 0x20-0x3F)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum NmtStateCommand {
    StartNode = 0x21,
    StopNode = 0x22,
    EnterPreOperational2 = 0x23,
    EnableReadyToOperate = 0x24,
    ResetNode = 0x28,
    ResetCommunication = 0x29,
    ResetConfiguration = 0x2A,
    SwReset = 0x2B,
}

impl TryFrom<u8> for NmtStateCommand {
    type Error = PowerlinkError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x21 => Ok(Self::StartNode),
            0x22 => Ok(Self::StopNode),
            0x23 => Ok(Self::EnterPreOperational2),
            0x24 => Ok(Self::EnableReadyToOperate),
            0x28 => Ok(Self::ResetNode),
            0x29 => Ok(Self::ResetCommunication),
            0x2A => Ok(Self::ResetConfiguration),
            0x2B => Ok(Self::SwReset),
            _ => Err(PowerlinkError::InvalidEnumValue),
        }
    }
}

/// Defines NMT Managing Command IDs used in ASnd(NMT_COMMAND) frames.
/// (Reference: EPSG DS 301, Appendix 3.7, 0x60-0x7F)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum NmtManagingCommand {
    NmtNetHostNameSet = 0x62,
    NmtFlushArpEntry = 0x63,
}

impl TryFrom<u8> for NmtManagingCommand {
    type Error = PowerlinkError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x62 => Ok(Self::NmtNetHostNameSet),
            0x63 => Ok(Self::NmtFlushArpEntry),
            _ => Err(PowerlinkError::InvalidEnumValue),
        }
    }
}

/// Defines NMT Service IDs that a CN can request via ASnd(NMT_REQUEST).
/// (Reference: EPSG DS 301, Table 145)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum NmtServiceRequest {
    IdentRequest = 0x01,
    StatusRequest = 0x02,
}

impl TryFrom<u8> for NmtServiceRequest {
    type Error = PowerlinkError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x01 => Ok(Self::IdentRequest),
            0x02 => Ok(Self::StatusRequest),
            _ => Err(PowerlinkError::InvalidEnumValue),
        }
    }
}

/// Represents a command or service that a CN can queue to be sent to the MN
/// via an `ASnd(NMT_REQUEST)` frame.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CnNmtRequest {
    Command(NmtStateCommand),
    Service(NmtServiceRequest),
}

impl CnNmtRequest {
    /// Returns the raw u8 ID for this command or service,
    /// to be used in the `NMTRequestedCommandID` field of an NMTRequest frame.
    pub fn as_u8(&self) -> u8 {
        match self {
            CnNmtRequest::Command(cmd) => *cmd as u8,
            CnNmtRequest::Service(srv) => *srv as u8,
        }
    }
}

/// Represents a command that the MN can queue to be sent
/// via an `ASnd(NMT_COMMAND)` frame.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MnNmtCommandRequest {
    State(NmtStateCommand),
    Managing(NmtManagingCommand),
}

impl MnNmtCommandRequest {
    /// Returns the raw u8 ID for this command,
    /// to be used in the `NMTCommandID` field of an NMTCommand frame.
    pub fn as_u8(&self) -> u8 {
        match self {
            MnNmtCommandRequest::State(cmd) => *cmd as u8,
            MnNmtCommandRequest::Managing(cmd) => *cmd as u8,
        }
    }
}

/// Defines events that can trigger a state transition in the NMT state machine.
///
/// These are derived from NMT commands or internal conditions.
/// (Reference: EPSG DS 301, Table 107 for CN, Figure 73 for MN)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NmtEvent {
    // --- NMT Command Events (received by CN, potentially generated by MN) ---
    /// Corresponds to the `NMTStartNode` command.
    StartNode,
    /// Corresponds to the `NMTStopNode` command.
    StopNode,
    /// Corresponds to the `NMTEnterPreOperational2` command.
    EnterPreOperational2,
    /// Corresponds to the `NMTEnableReadyToOperate` command.
    EnableReadyToOperate,
    /// Corresponds to the `NMTReset` command (hardware or other external reset).
    Reset,
    /// Corresponds to the `NMTSwReset` command.
    SwReset,
    /// Corresponds to the `NMTResetNode` command.
    ResetNode,
    /// Corresponds to the `NMTResetCommunication` command.
    ResetCommunication,
    /// Corresponds to the `NMTResetConfiguration` command.
    ResetConfiguration,

    // --- Internal/Timing Events ---
    /// Triggered internally or by receiving a POWERLINK frame. (Used by CN)
    EnterEplMode, // Maybe remove? Implicitly handled by Soc/SoA received.
    /// Triggered when a timer expires (e.g., NotActive timeout).
    Timeout,
    /// Triggered by a significant DLL or application error.
    Error,

    // --- Frame Reception Events ---
    /// Triggered when node received a SoC or SoA frame. (Used by CN NMT_CT2)
    SocSoAReceived,
    /// The CN received a SoC frame. (Used by CN NMT_CT4)
    SocReceived,
    /// Any powerlink frame received (Used by CN NMT_CT12).
    PowerlinkFrameReceived,

    // --- Controlled Node (CN) Specific Application Events ---
    /// Configuration completed and the CN is ready to operate. (Used by CN NMT_CT6)
    CnConfigurationComplete,

    // --- Managing Node (MN) Specific Internal Events ---
    /// All mandatory CNs identified. (Used by MN NMT_MT3)
    AllCnsIdentified,
    /// MN configuration complete and all mandatory CNs ready to operate. (Used by MN NMT_MT4)
    ConfigurationCompleteCnsReady,
    /// All mandatory CNs are confirmed to be in the Operational state.
    AllMandatoryCnsOperational,
}
